### ISSUE TITLE
How to run ipsec command for troubleshoot?

### ISSUE THREAD

**Issue by yuanlinios** [ibotty/atomic-ipsec-libreswan#3]
I installed the privileged container in atomic host and the service can be started successfully. From the systemd unit file, I can see the container is launched by systemd-nspawn. And I can see the running container with machinectl.

The problem is how can I run ipsec command like "ipsec whack --trafficstatus" for troubleshooting? It seems the ipsec command is only available inside the container. But "machinectl login ..." will prompt username/password which is unknown. And docker command cannot see the container.

**Comment by ibotty** [comment]
Hi,
unfortuntately I don't maintain that image anymore. I would recommend you check out the openshift ipsec documentation:
 https://docs.openshift.org/latest/admin_guide/ipsec.html

On atomic I would recommend you install libreswan via `rpm-ostree pkg-add`. It is such a fundamental package, that it does no harm in running it on the host (imo).


Regarding the problem AFAIR there was a way to get a shell, but I don't recall what it was nor do I have the infrastructure in place to check what it was. Sorry!

**Comment by yuanlinios** [comment]
That's OK. Thanks a lot for the information!
